### ISSUE TITLE
Microstation: master issue for major improvements

### ISSUE THREAD

**Issue by clairekuang** [specklesystems/speckle-sharp#1061]
The Bentley connectors should be improved to handle at minimum the Rhino test file elements and other send/receive features in DUI2. List of improvements include:

- [ ] Add a selection filter to connector sending (currently can't click on objects and send selected)
- [ ] Add `DisplayStyle` props to objects on send and receive
- [ ] Fix geometry conversions on send and receive, most notable: arc, ellipse, polycurve, closed nurbs **note** _breps received as meshes fixed already_
- [ ] Add smartsolid to speckle conversion (breps sent as meshes for now)

Receive:
![image](https://user-images.githubusercontent.com/16748799/155526350-ecaa2d16-4685-4965-aeda-087253723551.png)

Send:
![image](https://user-images.githubusercontent.com/16748799/155526436-677f4a41-5034-4005-9a05-b399186c94f7.png)

**Comment by garylzimmer** [comment]
Huge fan of this project since learning about it 5 minutes ago from the OSArch wiki!
Are there any plans to connect with Bentley Synchro or have any 4D/5D features implemented in Speckle?

**Comment by clairekuang** [comment]
@garylzimmer [Arup](https://github.com/arup-group) is the owner of the Microstation connectors! You can head over to their fork of [speckle-sharp](https://github.com/arup-group/speckle-sharp) fo Microstation development questions :)
